apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1
  - name: Tempo
    orgId: 1

datasources:
  # Prometheus 데이터소스
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
    editable: true

  # Loki 데이터소스 (로그)
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
    editable: true

  # Tempo 데이터소스 (트레이싱)
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
        lokiSearch: true
      tracesToMetrics:
        datasourceUid: prometheus
        queries:
          - name: 'Request rate'
            query: 'sum(rate(http_server_requests_seconds_count{$$__tags}[5m]))'
          - name: 'Error rate'
            query: 'sum(rate(http_server_requests_seconds_count{$$__tags,status=~"5.."}[5m]))'
      nodeGraph:
        enabled: true
    editable: true

  # PostgreSQL 데이터소스
  - name: PostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    url: holo-postgres:5432
    database: holo_oshi_db
    user: holo_user
    secureJsonData:
      password: holo_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    editable: true

  # Redis 데이터소스 (플러그인 필요)
  - name: Redis
    type: redis-datasource
    access: proxy
    orgId: 1
    url: redis://holo-redis:6379
    jsonData:
      poolSize: 10
      timeout: 10
    editable: true