# 개발 환경 설정
spring:
  profiles:
    active: dev
  
  # 개발 환경 데이터베이스
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/holo_oshi_db
    
  # 개발 환경 Redis
  data:
    redis:
      host: localhost
      port: 6380
      
  # 개발 환경 RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672

# 개발 환경 Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka123@localhost:50008/eureka/

# 개발 환경 로깅
logging:
  level:
    root: DEBUG
    com.holo.oshi: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data: DEBUG
    
# 개발 환경 추가 설정
debug: true
trace: false