server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_binary:
          endpoint: 0.0.0.0:6831
        thrift_compact:
          endpoint: 0.0.0.0:6832

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    compacted_block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /var/lib/tempo/traces
    wal:
      path: /var/lib/tempo/wal

querier:
  max_concurrent_queries: 20
  search:
    max_duration: 0

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: holo-msa
  storage:
    path: /var/lib/tempo/metrics
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

overrides:
  max_traces_per_user: 100000
  max_search_duration: 0